Repository ASFHyP3/hyp3-event-monitoring, pull requests merged in 2021-02, with the labels that each got.

#14 add bucket lifecycle policies
  cloudformation.yml
Labels: bumpless

#13 get file size from job instead of head_object
  harvest_products/src/harvest_products.py
  tests/test_harvest_products.py
Labels: bumpless

#15 Implement shared database module
  .github/workflows/static-analysis.yml
  api/requirements.txt
  api/src/api.py
  database/database/__init__.py
  database/database/database.py
  database/setup.py
  find_new/requirements.txt
  find_new/src/find_new.py
  harvest_products/requirements.txt
  harvest_products/src/harvest_products.py
  tests/conftest.py
  tests/test_api.py
  tests/test_database.py
  tests/test_find_new.py
  tests/test_harvest_products.py
Labels: bumpless

#16 add logging
  find_new/src/find_new.py
  harvest_products/src/harvest_products.py
Labels: bumpless

#18 harvest browse and thumbnail images
  harvest_products/requirements.txt
  harvest_products/src/harvest_products.py
  tests/test_harvest_products.py
Labels: bumpless

#19 hotfix DB name
  database/database/database.py
Labels: bug, bumpless

#20 fix query on primary key
  database/database/database.py
Labels: bug, bumpless

#22 fix typo in test_find_new mock payloads
  tests/test_find_new.py
Labels: bumpless

#23 submit insar jobs in find_new.add_product_for_processing
  find_new/requirements.txt
  find_new/src/find_new.py
  requirements-all.txt
  tests/test_find_new.py
  tests/test_harvest_products.py
Labels: bumpless

#24 increase memory of harvest_products lambda
  harvest_products/cloudformation.yml
Labels: bumpless

#25 Refactor harvest_products so HyP3 authentication only happens once
  harvest_products/src/harvest_products.py
  tests/test_harvest_products.py
Labels: bumpless

#26 refactor find_new so hyp3 authentication only happens once, eliminate…
  find_new/src/find_new.py
  tests/test_find_new.py
Labels: bumpless

#27 Create release.yml
  .github/workflows/release.yml
Labels: bumpless

#28 update deploy workflow for separate test/prod deployments, add releas…
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/deploy.yml
Labels: bumpless

#30 run find_new every hour, harvest_products every 30 minutes
  find_new/cloudformation.yml
  harvest_products/cloudformation.yml
Labels: bumpless

#31 only log granule name, not whole search api payload
  find_new/src/find_new.py
Labels: bumpless

#29 Update README.md
  README.md
Labels: bumpless

#32 submit all jobs for a granule as a single batch
  find_new/requirements.txt
  find_new/src/find_new.py
  harvest_products/requirements.txt
  harvest_products/src/harvest_products.py
  tests/test_find_new.py
Labels: bumpless

#34 fix readme typos
  README.md
Labels: bumpless

#36 Release handling of baseline api errors
  CHANGELOG.md
  find_new/src/find_new.py
  tests/test_find_new.py
Labels: patch

#38 Release checking for new granules more frequently
  CHANGELOG.md
  find_new/cloudformation.yml
Labels: patch
