Repository ASFHyP3/hyp3-event-monitoring, pull requests merged in 2024-07, with the labels that each got.

#82 add deploy concurrency
  .github/workflows/deploy.yml
Labels: bumpless

#83 Fix Import Issues with Werkzeug
  api/src/api.py
  requirements-api.txt
  tests/test_api.py
Labels: bumpless

#79 Release 0.1.0
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  api/requirements.txt
  api/src/api.py
  cloudformation.yml
  database/setup.py
  find_new/cloudformation.yml
  find_new/requirements.txt
  harvest_products/cloudformation.yml
  harvest_products/requirements.txt
  requirements-all.txt
  requirements-api.txt
  requirements-find-new.txt
  requirements-harvest-products.txt
  tests/conftest.py
  tests/test_api.py
  tests/test_find_new.py
Labels: minor

#89 Release v0.1.1
  CHANGELOG.md
  api/cloudformation.yml
  requirements-all.txt
  requirements-find-new.txt
Labels: patch
